sudo: required
services: 
  - docker

before_install:
  - docker build -t vatsal-patel03/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run vatsal-patel03/react-test npm test -- --coverage

after_success: 
  - docker build -t vatsal-patel03/multi-client ./client 
  - docker build -t vatsal-patel03/multi-nginx ./nginx
  - docker build -t vatsal-patel03/multi-server ./server
  - docker build -t vatsal-patel03/multi-worker ./worker