sudo: required
services: 
  - docker

before_install:
  - docker build -t vatsalp0310/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run vatsalp0310/react-test npm test -- --coverage

after_success: 
  - docker build -t vatsalp0310/multi-client ./client 
  - docker build -t vatsalp0310/multi-nginx ./nginx
  - docker build -t vatsalp0310/multi-server ./server
  - docker build -t vatsalp0310/multi-worker ./worker